### ISSUE TITLE
Unable to recover the dynamic and predict, when DataDrivenSolution's problem is Discrete DataDrivenProblem

### ISSUE THREAD

**Issue by MortezaBabazadehShareh** [SciML/DataDrivenDiffEq.jl#456] opened 2023-02-09 14:20 UTC
I work with DataDrivenDiffEq and DifferentialEquations packages. Whenever I define a Discrete DataDrivenProblem and solve the problem(for example by Sindy), I cannot recover the dynamic form the DataDrivenSolution and make predictions. This happens in a situation that error is reasonably low and the plot function shows a relatively match graphs. The point is, it is not the case when I have a Continuous DataDrivenProblem. Here I put a link to an example of this problem:

https://github.com/MortezaBabazadehShareh/MortezaBabazadehShareh/blob/main/simulated_SIR.jl

**Comment by ChrisRackauckas** [comment] 2023-02-13 13:24
It looks like this is just a duplicate of https://github.com/SciML/DataDrivenDiffEq.jl/issues/448

**Closed by ChrisRackauckas** 2023-02-13 13:24 UTC
